#define SCREEN_WIDTH 1280
#define SCREEN_HEIGHT 780
#define MAX_KEYBOARD_KEYS 350
#define FPS 60
#define SIDE_PLAYER 0
#define SIDE_ALIEN 1
#define PLAYER_SPEED 4
#define PLAYER_BULLET_SPEED 20
#define BOUND pow(PLAYER_SPEED, 1.7)
#define BULLET_RELOAD 8
#define ALIEN_BULLET_SPEED 8
#define MAX_STARS 450